import "@/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";

import ConvexClientProvider from "@/components/ConvexClientProvider";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={`${geist.variable} antialiased`}>
			<body>
				<ClerkProvider>
					<ConvexClientProvider>
						<main className="scanlines relative min-h-screen">
							<div className="screen relative">
								<canvas
									id="canvas"
									className="picture -z-10 absolute inset-0"
								/>
								<div className="overlay relative z-0">
									<div className="relative z-10">{children}</div>
									<Toaster />
								</div>
							</div>
						</main>
					</ConvexClientProvider>
				</ClerkProvider>
			</body>
		</html>
	);
}
